EXCEPTION TestException

LET x: Number := (TRY 5 TRAP TestException GIVES "five")
                                                 --<
